name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: latest

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r C:\Users\zatib\PycharmProjects\Tesla_price\requirements.txt

    - name: Run tests
      run: |
        pytest C:\Users\zatib\PycharmProjects\Tesla_price
