name: Python Package using Conda

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Set up Conda environment
      run: conda env create --file environment.yml
    - name: Activate Conda environment
      run: conda activate base
    - name: Add Conda Scripts to PATH
      env:
        CONDA: ${{ env.CONDA }}
      run: |
        echo "CONDA=$CONDA" >> $GITHUB_ENV
        echo "PATH=$CONDA\\Scripts;$PATH" >> $GITHUB_ENV
    - name: Lint with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: pytest
