name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: latest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib  # Прикладові пакети, можна додати ще

    - name: Run tests
      run: |
        pytest  
